name: rich_editor_gg
description: Flutter with a rich set of supported formatting options.
version: 1.1.2
homepage: https://github.com/JoseBarreto1/rich_editor

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  mime: ^1.0.5
  image_picker: ^1.1.2
  flutter_widget_from_html_core: ^0.15.1
  flutter_colorpicker: ^1.1.0
  path: ^1.9.0
  xml2json: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_inappwebview_android:
    git:
      url: https://github.com/EArminjon/flutter_inappwebview.git
      path: flutter_inappwebview_android
      ref: 4b781b6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/editor/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
